### ISSUE TITLE
SemanticUI with semantic-ui-react semantic-ui-less

### ISSUE THREAD

**Issue by agustif** [odiumediae/webpacker#1]
I was trying to use your boilerplate and add SemanticUI (LESS Version) to this by myself with not much success.

Would you help if I fork and make a PR?

Thanks!

**Comment by agustif** [comment]
So I kept programming until 5AM and I got it working.

I feel silly because I was mix and matching from another tutorial on webpack2 and Semantic-ui, but innecessarily doing the JS part (when, react's semantic-ui-react manages it all) 

FFS, I was even installing and loading jquery LOL

Anyway, I got it kinda working, should I tidy things up and PR with Semantic-UI less working? 

It's kinda easy though, maybe just documenting in a blogpost would suffice!

![screenshot 2017-04-26 05 04 43](https://cloud.githubusercontent.com/assets/6601142/25429211/e055f4d4-2a3d-11e7-9cc2-7feb3ba50da2.png)

**Comment by odiumediae** [comment]
I'm glad you got it working, but this starter kit is meant to be used with Stylus, not LESS, meaning I don't want to maintain different versions of the kit. But of course you can always fork it and use Semantic UI and LESS with it, I'd like to see that and link your project in this project's README.md, if you like.

**Comment by agustif** [comment]
@odiumediae Yeah that makes total sense, I didn't have any preference for a css preprocessor but semantic-ui doesn't seem to have stylus support (https://www.npmjs.com/package/semantic-ui-stylus) not official and 2y old code...
