### ISSUE TITLE
text assets is not working 

### ISSUE THREAD

**Issue by andrew-oko-odion** [odiumediae/webpacker#3]
Hello

Please I would like to know how you would include text assets into this application 

All Attempt to reference the full path or the partial path did not work for me. 

Please I need help, perhaps  an example. 

```
import "semantic-ui-css/semantic.css";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";

```
All the above is not working for me.

**Comment by odiumediae** [comment]
You need the appropriate loaders for Webpack and configuring Webpack is not in the scope of this project. I'm closing this issue, because it has nothing to do with Webpacker.
